### ISSUE TITLE
Hacer vídeos del juego para la presentación

### ISSUE THREAD

**Issue by 0xAdriaTorralba** [EnginyeriaSofwareUB/ES2017F1#105]
Criterios de Aceptación: 

- [x] Hacer unos videos para poner en la página web y presentar el día 20 de diciembre.

Tiempo: 2h.

**Comment by ainafem** [comment]
Yo no quiero hacer esto D: A no ser que sea el de presentación primero, los otros vídeos que tenemos que enseñar no xD

**Comment by ghost** [comment]
Done! S'ha fet un vídeo de la Slothapedia, un altre d'un extracte d'una partida 1 vs. 1 i un altre amb el tutorial sencer.
