### ISSUE TITLE
Implementació interfície gràfica del joc (partida)

### ISSUE THREAD

**Issue by ainafem** [EnginyeriaSofwareUB/ES2017F1#20]
Acceptance criteria:

- [x] La informació s'ha d'ensenyar abaix, centrada en la pantalla.
- [x]  Ha de canviar segons el torn del peresós que sigui.
- [ ]  S'ha de la informació de forma activa (per exemple, ús dels ability points).

**Comment by Ardaghor** [comment]
Done
