### ISSUE TITLE
Modificación funcionamiento cámara

### ISSUE THREAD

**Issue by 0xAdriaTorralba** [EnginyeriaSofwareUB/ES2017F1#36]
Modificar el comportamiento de la cámara dentro de la escena para que se centre en el sloth que le toca el turno, se pueda mover la cámara con el ratón cuando se acerca éste al límite de la pantalla y hacer que la cámara siga el proyectil cuando un Sloth lo lanza.

Criterios de Aceptación:

- [ ] La cámara se centra en el Sloth que le toca el turno.

- [ ] La cámara se puede mover con el ratón dentro de la pantalla de juego.

- [x] La cámara sigue un proyectil cuando un Sloth lo lanza.

**Comment by ainafem** [comment]
La cámara no se centra en el sloth cuando le toca el turno.

La cámara se puede mover con el ratón, pero el movimiento es excesivo y marea. Se tiene que cambiar.
