### ISSUE TITLE
Añadir fondos en el juego

### ISSUE THREAD

**Issue by 0xAdriaTorralba** [EnginyeriaSofwareUB/ES2017F1#43]
Añadir fondos en diversas escenas de la aplicación.

Criterios de Aceptación: 

- [x] Añadir fondo a la escena de Slothapedia.

- [x] Añadir fondo a la escena de Juego.

**Comment by darkmaus** [comment]
Ambos fondos colocados, en la escena de Juego envuelve la escena por si la cámara en algun momento tiene un movimiento en 3 dimensiones
