### ISSUE TITLE
Destrucción de Terreno

### ISSUE THREAD

**Issue by 0xAdriaTorralba** [EnginyeriaSofwareUB/ES2017F1#46]
Implementar una Habilidad que destruya un trozo de terreno en un radio predeterminado.

Criterios de Aceptación:
- [ ] Cuando se selecciona la habilidad de destrucción de terreno de un Sloth y se selecciona una zona en el mapa, el terreno de dicha zona deberá desaparecer sin comprometer el terreno adyacente.

**Comment by silensrunners** [comment]
Done.
