### ISSUE TITLE
Cambiar gravedad y colocar los Sloths en los arboles

### ISSUE THREAD

**Issue by 0xAdriaTorralba** [EnginyeriaSofwareUB/ES2017F1#47]
Cambiar la gravedad de los objetos Sloth para que se puedan subir encima de las hojas de los arboles.

Criterios de Aceptación:

- [x] Cuando empieza la partida los Sloths tienen que aparecer encima de los arboles.
- [ ] El movimiento del Sloth tiene que ser sobre las hojas, no sobre el terreno.

**Comment by silensrunners** [comment]
Done. Falta hacer que aparezcan aleatoriamente sobre los árboles cuando empieza la partida.
