### ISSUE TITLE
Cambiar cursor por una pata de Sloth

### ISSUE THREAD

**Issue by 0xAdriaTorralba** [EnginyeriaSofwareUB/ES2017F1#51]
Dibujar un modelo de una pata de Sloth y cambiarlo por el cursor dentro de la aplicación

Criterios de Aceptación:

- [x] Una vez iniciado el juego en la imagen del cursor debe aparecer una pata de Sloth.

**Comment by darkmaus** [comment]
Revisar en el peer review si es del gusto de todos
