### ISSUE TITLE
Corrección de cámara 1

### ISSUE THREAD

**Issue by darkmaus** [EnginyeriaSofwareUB/ES2017F1#61]
- [x] Poner la camara estilo age of empires y que se mueva  en vertical
- [x]  Poner zoom a la camara con la rueda del ratón, para que se vea el mapa.
- 4 horas.

**Comment by asegursa** [comment]
1) Lo de que se vea estilo Age of Empires es que ahora está demasiado horizontal con respecto al mapa, ¿no?

**Comment by asegursa** [comment]
En este commit --> #7930c9369c384aa8643982dced259e61ed96656b corrijo la issue.

Cierro issue.

**Comment by ghost** [comment]
En este commit --> 7930c93 corrijo la issue.

Cierro issue!
