### ISSUE TITLE
Slothapedia rework

### ISSUE THREAD

**Issue by darkmaus** [EnginyeriaSofwareUB/ES2017F1#63]
- [x] Poner el modelo que ocupe todo el hueco y que salgan los paneles pero en blanco.
- [x] Highlight del botón de la habilidad seleccionada.

**Comment by ainafem** [comment]
El rework del modelo está hecho, pero falta que el diseñador ponga los modelos que finalmente queríamos y que NO CAMBIE EL NOMBRE O LA VAMOS A LIAR POR FAVOR.
