### ISSUE TITLE
Implementació dels torns

### ISSUE THREAD

**Issue by ainafem** [EnginyeriaSofwareUB/ES2017F1#7]
Creació d'un algorisme que permeti moure's dins el mapa respectant uns torns.

Acceptance criteria:

- [x] Que no es pugui moure un objecte d'un equip si no és al seu torn.
- [x] Que efectivament es pugui moure l'equip quan és el seu torn.
- [x] Que es pugui passar de torn amb un botó o tecla.

**Comment by Ardaghor** [comment]
El cambio de turnos se efectúa adecuadamente. Cuando le toca el turno a un perezoso, el otro no se puede mover ni realizar ninguna acción (como disparar). Se puede pasar el turno pulsando un botón de la pantalla de juego.
