### ISSUE TITLE
Arreglar modelos de los sloths

### ISSUE THREAD

**Issue by Ardaghor** [EnginyeriaSofwareUB/ES2017F1#79]
Acceptance Criteria:

- [x] Mejor modelos de Sloths.

Tiempo: 2h.

**Comment by ghost** [comment]
Se ha terminado hoy, al final. Lo cerramos pero lo volvimos a abrir para probar si los nuevos sloths quedan bien o no en la escena. Ahora están terminados y falta probarlos en la escena. Cierro porque están terminados.
