### ISSUE TITLE
Poner los Sloths en el GameOver

### ISSUE THREAD

**Issue by 0xAdriaTorralba** [EnginyeriaSofwareUB/ES2017F1#88]
Criterios de Aceptación:
- [x] Cuando se acaba la partida deben aparecer Sloths volando en la pantalla de GameOver.

Tiempo: 1 hora.

**Comment by ainafem** [comment]
SOLVED.
Y SI ALGUIEN ME LOS DESHACE ES QUE ME LO VOY A COMER POR DIOS MIS SLOTHS QUIERO DEJAR DE PONERLOS AHÍ UNA Y OTRA VEZ.
