### ISSUE TITLE
Hacer página web

### ISSUE THREAD

**Issue by 0xAdriaTorralba** [EnginyeriaSofwareUB/ES2017F1#95]
Criterios de Aceptación:

- [x] Hacer una página web para promocionar el juego.

Tiempo:
Albert --> 5 horas.
José Peña --> 6 horas.

**Comment by ghost** [comment]
A falta de que afegim algun vídeo més d'última hora, que l'afegirem en res, deixo tancada la issue perquè els altres 3 vídeos ja estan a la web.
