### ISSUE TITLE
Terminar habilidades

### ISSUE THREAD

**Issue by jlgz** [EnginyeriaSofwareUB/ES2017F1#98]
Acceptance criteria:

- [x] Que se puedan utilizar todas las habilidades:
Bola de fuego.
Muro de hielo.
Proyectil cósmico.
Hacha.
Heal.
Link del tanque.
Escudos.
Flecha normal.
Flecha eléctrica.
Flecha veneno.
Bola de cura.
Cadenas del healer.
Teleport.
Muro con frutas.
Daño a distancia.

Tiempo: 6 horas.

**Comment by ghost** [comment]
Cerramos issue!
